/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/JIksIw18zUV
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { IBM_Plex_Sans } from 'next/font/google'

ibm_plex_sans({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { CardContent, CardHeader, Card } from "@/components/ui/card"
import { Button } from "@/components/ui/button"

export function Design1() {
  return (
    (<div className="flex flex-col min-h-[100dvh]">
      <header className="px-4 lg:px-6 h-14 flex items-center">
        <Link className="flex items-center justify-center" href="#">
          <PawPrintIcon className="h-6 w-6" />
          <span className="sr-only">Paws for a Cause</span>
        </Link>
        <nav className="ml-auto flex gap-4 sm:gap-6">
          <Link
            className="text-sm font-medium hover:underline underline-offset-4"
            href="#">
            Learn
          </Link>
          <Link
            className="text-sm font-medium hover:underline underline-offset-4"
            href="#">
            Adopt
          </Link>
          <Link
            className="text-sm font-medium hover:underline underline-offset-4"
            href="#">
            Donate
          </Link>
          <Link
            className="text-sm font-medium hover:underline underline-offset-4"
            href="#">
            About
          </Link>
        </nav>
      </header>
      <main className="flex-1">
        <section className="w-full py-12 md:py-24 lg:py-32 bg-[#F9F9F9] dark:bg-gray-800">
          <div className="container px-4 md:px-6">
            <div
              className="grid items-center gap-6 lg:grid-cols-[1fr_500px] lg:gap-12 xl:grid-cols-[1fr_550px]">
              <div className="flex flex-col justify-center space-y-4">
                <div className="space-y-2">
                  <div
                    className="inline-block rounded-lg bg-[#FFF0F0] px-3 py-1 text-sm dark:bg-gray-700">
                    End Animal Cruelty
                  </div>
                  <h1
                    className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl lg:text-6xl/none">
                    Paws for a Cause
                  </h1>
                  <p className="max-w-[700px] text-gray-500 md:text-xl dark:text-gray-400">
                    Join us in our mission to educate and empower people to take action against animal cruelty and
                    provide a safe haven for stray animals.
                  </p>
                </div>
                <div className="flex flex-col gap-2 min-[400px]:flex-row">
                  <Link
                    className="inline-flex h-9 items-center justify-center rounded-md bg-[#FF6B6B] px-4 py-2 text-sm font-medium text-gray-50 shadow transition-colors hover:bg-[#FF6B6B]/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-[#FF6B6B] disabled:pointer-events-none disabled:opacity-50 dark:bg-[#FF6B6B] dark:text-gray-900 dark:hover:bg-[#FF6B6B]/90 dark:focus-visible:ring-[#FF6B6B]"
                    href="#">
                    Adopt a Pet
                  </Link>
                  <Link
                    className="inline-flex h-9 items-center justify-center rounded-md border border-[#FF6B6B] bg-white px-4 py-2 text-sm font-medium shadow-sm transition-colors hover:bg-gray-100 hover:text-[#FF6B6B] focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-[#FF6B6B] disabled:pointer-events-none disabled:opacity-50 dark:border-[#FF6B6B] dark:bg-gray-950 dark:hover:bg-gray-800 dark:hover:text-[#FF6B6B] dark:focus-visible:ring-[#FF6B6B]"
                    href="#">
                    Donate
                  </Link>
                </div>
              </div>
              <img
                alt="Pets"
                className="mx-auto aspect-video overflow-hidden rounded-xl object-cover object-center sm:w-full lg:order-last"
                height="310"
                src="/placeholder.svg"
                width="550" />
            </div>
          </div>
        </section>
        <section className="w-full py-12 md:py-24 lg:py-32" id="learn">
          <div className="container px-4 md:px-6">
            <div
              className="flex flex-col items-center justify-center space-y-4 text-center">
              <div className="space-y-2">
                <div
                  className="inline-block rounded-lg bg-[#FFF0F0] px-3 py-1 text-sm dark:bg-gray-700">
                  Learn About Animal Cruelty
                </div>
                <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">The Harsh Realities</h2>
                <p
                  className="max-w-[900px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                  Educate yourself on the devastating impacts of animal cruelty and how you can make a difference.
                </p>
              </div>
            </div>
            <div
              className="mx-auto grid max-w-5xl items-start gap-6 py-12 lg:grid-cols-2 lg:gap-12">
              <img
                alt="Animal Cruelty"
                className="mx-auto aspect-video overflow-hidden rounded-xl object-cover object-center sm:w-full lg:order-last"
                height="310"
                src="/placeholder.svg"
                width="550" />
              <div className="flex flex-col justify-center space-y-4">
                <ul className="grid gap-6">
                  <li>
                    <div className="grid gap-1">
                      <h3 className="text-xl font-bold">Puppy Mills</h3>
                      <p className="text-gray-500 dark:text-gray-400">
                        Puppy mills are commercial dog breeding facilities that prioritize profit over the well-being of
                        the animals.
                      </p>
                    </div>
                  </li>
                  <li>
                    <div className="grid gap-1">
                      <h3 className="text-xl font-bold">Factory Farming</h3>
                      <p className="text-gray-500 dark:text-gray-400">
                        Factory farming subjects animals to unnatural and inhumane living conditions, often leading to
                        physical and psychological distress.
                      </p>
                    </div>
                  </li>
                  <li>
                    <div className="grid gap-1">
                      <h3 className="text-xl font-bold">Wildlife Trafficking</h3>
                      <p className="text-gray-500 dark:text-gray-400">
                        The illegal trade of wild animals for pets, traditional medicine, or entertainment purposes is a
                        major contributor to the decline of many species.
                      </p>
                    </div>
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </section>
        <section
          className="w-full py-12 md:py-24 lg:py-32 bg-[#F9F9F9] dark:bg-gray-800"
          id="adopt">
          <div className="container px-4 md:px-6">
            <div
              className="flex flex-col items-center justify-center space-y-4 text-center">
              <div className="space-y-2">
                <div
                  className="inline-block rounded-lg bg-[#FFF0F0] px-3 py-1 text-sm dark:bg-gray-700">
                  Adopt a Pet
                </div>
                <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">Find Your Furry Friend</h2>
                <p
                  className="max-w-[900px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                  Browse our selection of adoptable pets and give a loving home to a deserving animal in need.
                </p>
              </div>
            </div>
            <div
              className="mx-auto grid max-w-5xl items-start gap-6 py-12 lg:grid-cols-3 lg:gap-8">
              <Card className="rounded-xl overflow-hidden shadow-md">
                <CardContent className="p-0">
                  <img
                    alt="Pet"
                    className="aspect-video object-cover"
                    height="300"
                    src="/placeholder.svg"
                    width="400" />
                </CardContent>
                <CardHeader className="p-4">
                  <div className="flex items-center justify-between">
                    <div>
                      <h3 className="text-lg font-bold">Buddy</h3>
                      <p className="text-sm text-gray-500 dark:text-gray-400">2-year-old Labrador Retriever</p>
                    </div>
                    <Button size="sm" variant="outline">
                      Adopt
                    </Button>
                  </div>
                </CardHeader>
              </Card>
              <Card className="rounded-xl overflow-hidden shadow-md">
                <CardContent className="p-0">
                  <img
                    alt="Pet"
                    className="aspect-video object-cover"
                    height="300"
                    src="/placeholder.svg"
                    width="400" />
                </CardContent>
                <CardHeader className="p-4">
                  <div className="flex items-center justify-between">
                    <div>
                      <h3 className="text-lg font-bold">Daisy</h3>
                      <p className="text-sm text-gray-500 dark:text-gray-400">4-year-old Domestic Shorthair Cat</p>
                    </div>
                    <Button size="sm" variant="outline">
                      Adopt
                    </Button>
                  </div>
                </CardHeader>
              </Card>
              <Card className="rounded-xl overflow-hidden shadow-md">
                <CardContent className="p-0">
                  <img
                    alt="Pet"
                    className="aspect-video object-cover"
                    height="300"
                    src="/placeholder.svg"
                    width="400" />
                </CardContent>
                <CardHeader className="p-4">
                  <div className="flex items-center justify-between">
                    <div>
                      <h3 className="text-lg font-bold">Milo</h3>
                      <p className="text-sm text-gray-500 dark:text-gray-400">1-year-old Mixed Breed</p>
                    </div>
                    <Button size="sm" variant="outline">
                      Adopt
                    </Button>
                  </div>
                </CardHeader>
              </Card>
            </div>
            <div className="flex justify-center space-x-4 mt-8">
              <Link
                className="inline-flex h-10 items-center justify-center rounded-md bg-[#FF6B6B] px-8 text-sm font-medium text-gray-50 shadow transition-colors hover:bg-[#FF6B6B]/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-[#FF6B6B] disabled:pointer-events-none disabled:opacity-50 dark:bg-[#FF6B6B] dark:text-gray-900 dark:hover:bg-[#FF6B6B]/90 dark:focus-visible:ring-[#FF6B6B]"
                href="#">
                View All Pets
              </Link>
            </div>
          </div>
        </section>
        <section className="w-full py-12 md:py-24 lg:py-32" id="donate">
          <div className="container px-4 md:px-6">
            <div
              className="flex flex-col items-center justify-center space-y-4 text-center">
              <div className="space-y-2">
                <div
                  className="inline-block rounded-lg bg-[#FFF0F0] px-3 py-1 text-sm dark:bg-gray-700">
                  Donate to Help
                </div>
                <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">Support Our Mission</h2>
                <p
                  className="max-w-[900px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                  Your donation can make a significant impact in the lives of animals in need. Help us provide essential
                  care, rehabilitation, and adoption services.
                </p>
              </div>
            </div>
            <div
              className="mx-auto grid max-w-5xl items-start gap-6 py-12 lg:grid-cols-2 lg:gap-12">
              <div className="flex flex-col justify-center space-y-4">
                <div className="space-y-2">
                  <h3 className="text-2xl font-bold">Your Donation Can:</h3>
                  <ul className="list-disc pl-6 space-y-2 text-gray-500 dark:text-gray-400">
                    <li>Provide food, shelter, and medical care for rescued animals</li>
                    <li>Fund rehabilitation programs to help animals recover and prepare for adoption</li>
                    <li>Support our educational initiatives to raise awareness about animal cruelty</li>
                    <li>Contribute to the rescue and rehabilitation of stray and abandoned animals</li>
                  </ul>
                </div>
                <div className="flex flex-col gap-2 min-[400px]:flex-row">
                  <Link
                    className="inline-flex h-10 items-center justify-center rounded-md bg-[#FF6B6B] px-8 text-sm font-medium text-gray-50 shadow transition-colors hover:bg-[#FF6B6B]/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-[#FF6B6B] disabled:pointer-events-none disabled:opacity-50 dark:bg-[#FF6B6B] dark:text-gray-900 dark:hover:bg-[#FF6B6B]/90 dark:focus-visible:ring-[#FF6B6B]"
                    href="#">
                    Donate Now
                  </Link>
                  <Link
                    className="inline-flex h-10 items-center justify-center rounded-md border border-[#FF6B6B] bg-white px-8 text-sm font-medium shadow-sm transition-colors hover:bg-gray-100 hover:text-[#FF6B6B] focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-[#FF6B6B] disabled:pointer-events-none disabled:opacity-50 dark:border-[#FF6B6B] dark:bg-gray-950 dark:hover:bg-gray-800 dark:hover:text-[#FF6B6B] dark:focus-visible:ring-[#FF6B6B]"
                    href="#">
                    Learn More
                  </Link>
                </div>
              </div>
            </div>
          </div>
        </section>
      </main>
    </div>)
  );
}

function PawPrintIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <circle cx="11" cy="4" r="2" />
      <circle cx="18" cy="8" r="2" />
      <circle cx="20" cy="16" r="2" />
      <path
        d="M9 10a5 5 0 0 1 5 5v3.5a3.5 3.5 0 0 1-6.84 1.045Q6.52 17.48 4.46 16.84A3.5 3.5 0 0 1 5.5 10Z" />
    </svg>)
  );
}
