/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/8GZApBjoira
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Tenor_Sans } from 'next/font/google'
import { Rubik } from 'next/font/google'

tenor_sans({
  subsets: ['latin'],
  display: 'swap',
})

rubik({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { CardContent, CardFooter, Card } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"

export function Design3() {
  return (
    (<div className="flex flex-col min-h-[100dvh]">
      <header className="px-4 lg:px-6 h-14 flex items-center">
        <Link className="flex items-center justify-center" href="#">
          <PawPrintIcon className="h-6 w-6" />
          <span className="sr-only">Paws for a Cause</span>
        </Link>
        <nav className="ml-auto flex gap-4 sm:gap-6">
          <Link
            className="text-sm font-medium hover:underline underline-offset-4"
            href="#">
            About
          </Link>
          <Link
            className="text-sm font-medium hover:underline underline-offset-4"
            href="#">
            Impact
          </Link>
          <Link
            className="text-sm font-medium hover:underline underline-offset-4"
            href="#">
            Adopt
          </Link>
          <Link
            className="text-sm font-medium hover:underline underline-offset-4"
            href="#">
            Donate
          </Link>
        </nav>
      </header>
      <main className="flex-1">
        <section
          className="w-full py-12 md:py-24 lg:py-32 xl:py-48 bg-[#f5f5f5] dark:bg-gray-900">
          <div className="container px-4 md:px-6">
            <div
              className="grid gap-6 lg:grid-cols-[1fr_400px] lg:gap-12 xl:grid-cols-[1fr_600px]">
              <div className="flex flex-col justify-center space-y-4">
                <div className="space-y-2">
                  <h1
                    className="text-3xl font-bold tracking-tighter sm:text-5xl xl:text-6xl/none text-[#333] dark:text-white">
                    Paws for a Cause
                  </h1>
                  <p className="max-w-[600px] text-gray-500 md:text-xl dark:text-gray-400">
                    Empowering compassion and ending animal cruelty. Adopt, donate, and make a difference.
                  </p>
                </div>
                <div className="flex flex-col gap-2 min-[400px]:flex-row">
                  <Link
                    className="inline-flex h-10 items-center justify-center rounded-md bg-[#ff6b6b] px-8 text-sm font-medium text-white shadow transition-colors hover:bg-[#ff4d4d] focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-[#ff6b6b] disabled:pointer-events-none disabled:opacity-50 dark:bg-[#ff6b6b] dark:text-white dark:hover:bg-[#ff4d4d] dark:focus-visible:ring-[#ff6b6b]"
                    href="#">
                    Adopt a Pet
                  </Link>
                  <Link
                    className="inline-flex h-10 items-center justify-center rounded-md border border-[#ff6b6b] bg-white px-8 text-sm font-medium shadow-sm transition-colors hover:bg-[#ff6b6b] hover:text-white focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-[#ff6b6b] disabled:pointer-events-none disabled:opacity-50 dark:border-[#ff6b6b] dark:bg-gray-900 dark:hover:bg-[#ff6b6b] dark:hover:text-white dark:focus-visible:ring-[#ff6b6b]"
                    href="#">
                    Donate
                  </Link>
                </div>
              </div>
              <img
                alt="Hero"
                className="mx-auto aspect-video overflow-hidden rounded-xl object-cover object-center sm:w-full lg:order-last"
                height={310}
                src="/placeholder.svg"
                width={550} />
            </div>
          </div>
        </section>
        <section className="w-full py-12 md:py-24 lg:py-32" id="about">
          <div className="container px-4 md:px-6">
            <div
              className="flex flex-col items-center justify-center space-y-4 text-center">
              <div className="space-y-2">
                <h2
                  className="text-3xl font-bold tracking-tighter sm:text-5xl text-[#333] dark:text-white">
                  About Paws for a Cause
                </h2>
                <p
                  className="max-w-[900px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                  Paws for a Cause is a non-profit organization dedicated to ending animal cruelty and providing a safe
                  haven for stray and abandoned animals. We believe that every creature deserves a loving home and the
                  chance to thrive.
                </p>
              </div>
            </div>
          </div>
        </section>
        <section
          className="w-full py-12 md:py-24 lg:py-32 bg-[#f5f5f5] dark:bg-gray-900"
          id="impact">
          <div className="container px-4 md:px-6">
            <div
              className="flex flex-col items-center justify-center space-y-4 text-center">
              <div className="space-y-2">
                <h2
                  className="text-3xl font-bold tracking-tighter sm:text-5xl text-[#333] dark:text-white">
                  The Impact of Animal Cruelty
                </h2>
                <p
                  className="max-w-[900px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                  Animal cruelty has devastating consequences, both for the animals and the communities they live in.
                  From physical and emotional suffering to the spread of disease and environmental degradation, the
                  impact of animal cruelty is far-reaching and must be addressed.
                </p>
              </div>
              <div
                className="mx-auto grid max-w-5xl items-center gap-6 py-12 lg:grid-cols-2 lg:gap-12">
                <img
                  alt="Animal Cruelty"
                  className="mx-auto aspect-video overflow-hidden rounded-xl object-cover object-center sm:w-full lg:order-last"
                  height={310}
                  src="/placeholder.svg"
                  width={550} />
                <div className="flex flex-col justify-center space-y-4">
                  <ul className="grid gap-6">
                    <li>
                      <div className="grid gap-1">
                        <h3 className="text-xl font-bold text-[#333] dark:text-white">
                          Physical and Emotional Suffering
                        </h3>
                        <p className="text-gray-500 dark:text-gray-400">
                          Animals subjected to cruelty experience immense physical pain and psychological trauma, often
                          leading to long-term health issues and behavioral problems.
                        </p>
                      </div>
                    </li>
                    <li>
                      <div className="grid gap-1">
                        <h3 className="text-xl font-bold text-[#333] dark:text-white">Spread of Disease</h3>
                        <p className="text-gray-500 dark:text-gray-400">
                          Neglected and abused animals can become vectors for the transmission of diseases, posing a
                          risk to both animal and human populations.
                        </p>
                      </div>
                    </li>
                    <li>
                      <div className="grid gap-1">
                        <h3 className="text-xl font-bold text-[#333] dark:text-white">Environmental Degradation</h3>
                        <p className="text-gray-500 dark:text-gray-400">
                          The mistreatment of animals can contribute to the destruction of natural habitats and the
                          disruption of delicate ecosystems.
                        </p>
                      </div>
                    </li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </section>
        <section className="w-full py-12 md:py-24 lg:py-32" id="adopt">
          <div className="container px-4 md:px-6">
            <div
              className="flex flex-col items-center justify-center space-y-4 text-center">
              <div className="space-y-2">
                <h2
                  className="text-3xl font-bold tracking-tighter sm:text-5xl text-[#333] dark:text-white">
                  Adopt a Pet
                </h2>
                <p
                  className="max-w-[900px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                  Browse our selection of rescued and rehabilitated animals in need of loving homes. By adopting, you
                  can provide a second chance and make a meaningful difference in the life of a furry friend.
                </p>
              </div>
              <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-6">
                <Card className="rounded-lg overflow-hidden shadow-md">
                  <CardContent className="p-0">
                    <img
                      alt="Dog"
                      className="aspect-video object-cover"
                      height={300}
                      src="/placeholder.svg"
                      width={400} />
                  </CardContent>
                  <CardFooter className="p-4">
                    <div className="flex flex-col gap-2">
                      <h3 className="text-xl font-bold text-[#333] dark:text-white">Buddy</h3>
                      <p className="text-gray-500 dark:text-gray-400">
                        Friendly, energetic 3-year-old Labrador mix. Loves playing fetch and going on long walks.
                      </p>
                      <Link
                        className="inline-flex h-9 items-center justify-center rounded-md bg-[#ff6b6b] px-4 py-2 text-sm font-medium text-white shadow transition-colors hover:bg-[#ff4d4d] focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-[#ff6b6b] disabled:pointer-events-none disabled:opacity-50 dark:bg-[#ff6b6b] dark:text-white dark:hover:bg-[#ff4d4d] dark:focus-visible:ring-[#ff6b6b]"
                        href="#">
                        Adopt Buddy
                      </Link>
                    </div>
                  </CardFooter>
                </Card>
                <Card className="rounded-lg overflow-hidden shadow-md">
                  <CardContent className="p-0">
                    <img
                      alt="Cat"
                      className="aspect-video object-cover"
                      height={300}
                      src="/placeholder.svg"
                      width={400} />
                  </CardContent>
                  <CardFooter className="p-4">
                    <div className="flex flex-col gap-2">
                      <h3 className="text-xl font-bold text-[#333] dark:text-white">Whiskers</h3>
                      <p className="text-gray-500 dark:text-gray-400">
                        Affectionate, playful 2-year-old tabby cat. Loves cuddles and chasing toys.
                      </p>
                      <Link
                        className="inline-flex h-9 items-center justify-center rounded-md bg-[#ff6b6b] px-4 py-2 text-sm font-medium text-white shadow transition-colors hover:bg-[#ff4d4d] focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-[#ff6b6b] disabled:pointer-events-none disabled:opacity-50 dark:bg-[#ff6b6b] dark:text-white dark:hover:bg-[#ff4d4d] dark:focus-visible:ring-[#ff6b6b]"
                        href="#">
                        Adopt Whiskers
                      </Link>
                    </div>
                  </CardFooter>
                </Card>
                <Card className="rounded-lg overflow-hidden shadow-md">
                  <CardContent className="p-0">
                    <img
                      alt="Rabbit"
                      className="aspect-video object-cover"
                      height={300}
                      src="/placeholder.svg"
                      width={400} />
                  </CardContent>
                  <CardFooter className="p-4">
                    <div className="flex flex-col gap-2">
                      <h3 className="text-xl font-bold text-[#333] dark:text-white">Hoppy</h3>
                      <p className="text-gray-500 dark:text-gray-400">
                        Gentle, curious 1-year-old rabbit. Loves munching on carrots and exploring new spaces.
                      </p>
                      <Link
                        className="inline-flex h-9 items-center justify-center rounded-md bg-[#ff6b6b] px-4 py-2 text-sm font-medium text-white shadow transition-colors hover:bg-[#ff4d4d] focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-[#ff6b6b] disabled:pointer-events-none disabled:opacity-50 dark:bg-[#ff6b6b] dark:text-white dark:hover:bg-[#ff4d4d] dark:focus-visible:ring-[#ff6b6b]"
                        href="#">
                        Adopt Hoppy
                      </Link>
                    </div>
                  </CardFooter>
                </Card>
              </div>
            </div>
          </div>
        </section>
        <section
          className="w-full py-12 md:py-24 lg:py-32 bg-[#f5f5f5] dark:bg-gray-900"
          id="donate">
          <div className="container px-4 md:px-6">
            <div
              className="flex flex-col items-center justify-center space-y-4 text-center">
              <div className="space-y-2">
                <h2
                  className="text-3xl font-bold tracking-tighter sm:text-5xl text-[#333] dark:text-white">
                  Donate to Our Cause
                </h2>
                <p
                  className="max-w-[900px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                  Your donation can make a real difference in the lives of animals in need. Help us provide food,
                  shelter, medical care, and rehabilitation services to rescue animals and find them loving homes.
                </p>
              </div>
              <div className="mx-auto w-full max-w-sm space-y-2">
                <form className="flex space-x-2">
                  <Input
                    className="max-w-lg flex-1"
                    placeholder="Enter donation amount"
                    type="number" />
                  <Button className="bg-[#ff6b6b] hover:bg-[#ff4d4d] text-white" type="submit">
                    Donate
                  </Button>
                </form>
                <p className="text-xs text-gray-500 dark:text-gray-400" />
              </div>
            </div>
          </div>
        </section>
      </main>
    </div>)
  );
}

function PawPrintIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <circle cx="11" cy="4" r="2" />
      <circle cx="18" cy="8" r="2" />
      <circle cx="20" cy="16" r="2" />
      <path
        d="M9 10a5 5 0 0 1 5 5v3.5a3.5 3.5 0 0 1-6.84 1.045Q6.52 17.48 4.46 16.84A3.5 3.5 0 0 1 5.5 10Z" />
    </svg>)
  );
}
